ARG base=nobodyxu/faiss:latest-with-src

FROM $base AS test

# Build /tmp/test/
ADD --chown=user:user makefile-test /tmp/test/Makefile
RUN cp tests/*.cpp tests/*.py /tmp/test/

# Download gtest to /tmp/test/
ADD --chown=user:user https://github.com/google/googletest/archive/release-1.8.0.tar.gz /tmp/
RUN tar xvzf /tmp/release-1.8.0.tar.gz && \
    mv googletest-release-1.8.0/googletest/ /tmp/test/gtest/

# Run the test
WORKDIR /tmp/test/
RUN make
