#!/bin/bash -ex

if [ ${DOCKER_TAG} != "latest" ]; then
    branch=${DOCKER_TAG}
else
    branch=master
fi

time docker build --target release  --build-arg branch=$branch -t nobodyxu/faiss:${DOCKER_TAG} .
time docker build --target with-src --build-arg branch=$branch -t nobodyxu/faiss:${DOCKER_TAG}-with-src .
