#!/bin/bash -ex

# Print debugging infomation
pwd
ls -ls

time docker build --target Installed -t nobodyxu/faiss:${DOCKER_TAG} .
exec time docker build --target with-src -t nobodyxu/faiss:${DOCKER_TAG}-with-src .
